[program:auto-order-quote]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/dsp_api/artisan queue:work --queue=auto-order-quote --tries=1 --timeout=720 --memory=1024
autostart=true
autorestart=true
user=www-data
numprocs=5
redirect_stderr=true
stdout_logfile=/var/www/html/dsp_api/storage/logs/auto_order_quote.log
