[program:credit_stock_up_export]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/dsp_api/artisan queue:work --queue=credit-stock-up:export --tries=3 --memory=1024 --timeout=240
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/dsp_api/storage/logs/credit-stock-up:export.log
