[program:laravel-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/dsp_api/artisan queue:work --queue=dsp
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/html/dsp_api/storage/logs/worker.log
