[program:push-goods-to-mabang]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/dsp_api/artisan queue:work --queue=push-goods-to-mabang --tries=4 --memory=1024 --timeout=240
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/html/dsp_api/storage/logs/push-goods-to-mabang.log