[program:sync_order]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/dsp_api/artisan queue:work --queue=sync_order_high,sync_order --timeout=720 --memory=1024
autostart=true
autorestart=true
user=www-data
numprocs=5
redirect_stderr=true
stdout_logfile=/var/www/html/dsp_api/storage/logs/sync_order.log
