<?php

namespace App\Services\Admin;

use App\Lib\Code;
use App\Models\AfterSalesWorkOrder;
use App\Models\AfterSalesWorkOrderLogs;
use App\Services\ExpressCompanies\KuaiDi\Exceptions\Exception;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use App\Exceptions\AccidentException;

/**
 * 管理端售后工单服务类
 * Class AfterSalesWorkOrderService
 * @package App\Services\Client
 * @author DonnyLiu <2365057581@qq.com>
 * @date 2024/9/6 16:51
 */
class AfterSalesWorkOrderService extends BaseService
{
    public $filterRules = [
        'status'        => ['=', 'status'],
        'work_order_id' => ['like', 'work_order_id'],
        'custom_id'     => ['=', 'custom_id'],
        'desc'          => ['like', 'desc'],
        'type'          => ['=', 'type'],
        'handle_admin_id'=> ['=', 'handle_admin_id'],
        'created_at'    => ['between', ['begin_date', 'end_date']],
    ];

    public const HANDLE_TYPE = 1; //处理操作
    public const CLAIM_TYPE = 2; //认领操作

    /**
     * 初始化
     * @param AfterSalesWorkOrder $model
     */
    public function __construct(AfterSalesWorkOrder $model)
    {
        $this->model = $model;
        $this->query = $model->newQuery();
        $this->formData = request()->all();
        $this->setFilterRules();
    }

    /**
     * 获取列表
     * @return \Illuminate\Pagination\LengthAwarePaginator
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 17:28
     */
    public function index()
    {
        if (!isset($this->formData['size'])) $this->formData['size'] = 20;

        $this->query->with(['custom', 'handleAdmin']);

        $this->query->latest();

        return parent::index();
    }

    /**
     * 获取详情
     * @param $id
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed|null
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 17:27
     */
    public function show($id)
    {
        $this->query->with(['custom', 'handleAdmin']);

        return $this->query->findOrFail($id); // TODO: Change the autogenerated stub
    }

    /**
     * 更新
     * @param $id
     * @param $data
     * @return bool
     * @throws \Illuminate\Validation\ValidationException
     * @throws Exception
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 17:57
     */
    public function update($id, $data)
    {
        validator($data, $this->getUpdateRules())->validate();

        $type = $data['operate_type'] ?? self::HANDLE_TYPE;
        if (!($workOrder = $this->show($id))) {
            throw new AccidentException('售后工单不存在', Code::OPERATE_FAIL);
        }

        if ($type == self::HANDLE_TYPE) {
            if ($workOrder->status != $this->model::HANDING_STATUS) {
                throw new AccidentException('工单不在处理中状态', Code::OPERATE_FAIL);
            }
            if ($workOrder->handle_admin_id != auth('admin')->id()) {
                throw new AccidentException('此工单不属于你认领，无权限操作', Code::OPERATE_FAIL);
            }

            $updateData = [
                'status'        => $data['status'],
                'handle_result' => $data['handle_result'] ?? '',
                'handle_time'   => Carbon::now()->toDateTimeString()
            ];
        } else {
            if ($workOrder->status != $this->model::PENDING_HANDLE_STATUS || $workOrder->handle_admin_id > 0) {
                throw new AccidentException('工单不在待处理中状态',Code::OPERATE_FAIL);
            }

            $updateData = [
                'status' => $this->model::HANDING_STATUS,
                'handle_admin_id' => auth('admin')->id(),
                'handle_time' => Carbon::now()->toDateTimeString()
            ];
        }

        try {
            $updateData['status'] = (int) $updateData['status'];

            $result = $workOrder->update($updateData);
            if ($result) {
                //记录工单操作日志
                AfterSalesWorkOrderLogs::query()->create([
                    'work_order_id' => $id,
                    'custom_id'     => $workOrder->custom_id,
                    'type'          => $updateData['status'],
                    'content'       => $this->getLogsContent(auth('admin')->id(), $workOrder->work_order_id, $updateData['status']),
                    'handle_id'     => auth('admin')->id(),
                ]);
            }
        } catch (\Exception $e) {
            return false;
        }

        return true;
    }

    /**
     * 获取工单类型
     * @return array
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 19:35
     */
    public function getTypeList()
    {
        return $this->model->getTypeList();
    }

    /**
     * 获取工单日志操作记录内容
     * @param int $adminId
     * @param string $workOrderId
     * @param int $status
     * @return string
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 19:23
     */
    public function getLogsContent(int $adminId, string $workOrderId, int $status)
    {
        $content = "管理员ID：{$adminId}，将工单号：{$workOrderId} ";
        return match ($status) {
            $this->model::HANDING_STATUS => $content . '改为处理中',
            $this->model::HANDLE_COMPLETE_STATUS => $content . '已处理完成',
            $this->model::CLOSED_STATUS => $content . '已关闭',
        };
    }

    /**
     * 获取更新的验证规则
     * @return string[]
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 17:55
     */
    public function getUpdateRules()
    {
        return [
            'operate_type'  => 'required',
            'status'        => 'required_if:operate_type,1|in:3,4|nullable',
            'handle_result' => 'required_if:operate_type,1|max:500|nullable',
        ];
    }
}
