<?php

namespace App\Services\Admin;


use App\Exceptions\AccidentException;

use App\Lib\Code;
use App\Models\EmailTemplate;
use App\Models\MailSmtpConfig;
use App\Services\ApiResponseService;
use App\Services\ExpressCompanies\KuaiDi\Exceptions\Exception;
use Illuminate\Mail\MailManager;
use Illuminate\Support\Facades\DB;
use function PHPUnit\Framework\throwException;

class EmailTemplateService extends BaseService
{

    public function __construct(EmailTemplate $model)
    {
        $this->model = $model;
        $this->query = $model->newQuery();
        $this->formData = request()->all();
        $this->setFilterRules();
    }

    /**
     * @desc 获取邮件模板列表
     * @return \Illuminate\Pagination\LengthAwarePaginator
     */
    public function index()
    {
        if (!empty($this->formData['type'])) {
            $this->query->where('type', $this->formData['type']);
        }
        return parent::index(); // TODO: Change the autogenerated stub
    }

    /**
     * @desc 保存邮件模板
     * @param $data
     * @return mixed
     * @throws \Illuminate\Validation\ValidationException
     */
    public function saveEmailTemplate($data)
    {
        validator($data, $this->rules())->validate();

        return DB::transaction(function () use ($data) {
            $this->model::query()->updateOrCreate(
                ['type' => $data['type'] ?? 0],
                [
                    'title' => $data['title'] ?? '',
                    'type' => $data['type'] ?? '',
                    'content' => json_encode(['default' => $data['content'] ?? '']),
                ]
            );
            return true;
        });
    }

    /**
     * @desc 删除邮件模板
     * @param array $id
     * @return bool
     */
    public function delete(array $id): bool
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

    public function setEmailTemplateStatus(array $params)
    {
        $emailTemplateData = $this->query->where('id', $params['id'] ?? 0)->first();
        if (!$emailTemplateData) {
            throw new AccidentException('邮件模板信息不存在', Code::OPERATE_FAIL);
        }
        DB::beginTransaction();
        try {
            $this->query->where('type', $emailTemplateData['type'])->update(['enabled' => 0]);
            $this->query->where('id', $params['id'])->update(['enabled' => $params['enabled'] == 'true' ? 1 : 0]);
            DB::commit();
            return true;
        } catch (\Throwable $e) {
            DB::rollBack();
            throw new AccidentException('邮件模板状态设置失败', Code::OPERATE_FAIL);
        }
    }

    public function rules()
    {
        return [
            'title' => 'required|string|max:50',
            'content' => 'sometimes|nullable|string',
            'type' => 'sometimes|nullable|integer',
            'enabled' => 'sometimes|nullable|integer',
        ];
    }

}
