<?php

/**
 * @Author: h9471
 * @Created: 2019/9/11 11:40
 */

namespace App\Services\Admin;

use App\Http\Resources\ExpressLineVASList;
use App\Jobs\Export\RegionServicePriceExport;
use App\Lib\Code;
use App\Models\ExcelExport;
use App\Models\ExpressLineRegion;
use App\Models\ExpressLineServicePrice;
use App\Models\ExpressLineVAS;
use App\Models\ExpressLineVAS as ServiceModel;
use App\Models\Order;
use Carbon\Carbon;
use Exception;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;
use Illuminate\Http\UploadedFile;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Vtiful\Kernel\Excel;
use App\Exceptions\AccidentException;

class ExpressLineServiceService extends BaseService
{
    use HasNameUniqueValidation,
        HasStatusSetting;

    public function __construct()
    {
        $this->request = request();
        $this->formData = $this->request->all();
        $this->model = new ServiceModel();
        $this->query = $this->model->newQuery();
        $this->setFilterRules();
    }

    /**
     * @param array $data
     * @param ServiceModel $service
     */
    protected static function updateTrans(array $data, ServiceModel $service): void
    {
        if ($data['name_translations'] ?? []) {
            $translations = collect($data['name_translations'])
                ->filter(fn($value) => $value)
                ->all();

            if ($translations) {
                $service->setTranslations('name', $translations);
            }

            $service->save();
        }

        if ($data['remark_translations'] ?? []) {
            $translations = collect($data['remark_translations'])
                ->filter(fn($value) => $value)
                ->all();

            if ($translations) {
                $service->setTranslations('remark', $translations);
            }

            $service->save();
        }
    }

    /**
     * @param $id
     * @return LengthAwarePaginator
     */
    public function serviceIndex($id)
    {
        return ExpressLineRegion::query()
            ->with(['servicePrices.service', 'areas'])
            ->where('express_line_id', $id)
            ->pageSize();
    }

    /**
     * @param $id
     * @return mixed
     */
    public function show($id)
    {
        $this->query->with(['prices', 'prices.region', 'prices.region.areas']);

        return parent::show($id); // TODO: Change the autogenerated stub
    }

    /**
     * @param $expId
     * @param array $data
     * @return mixed
     * @throws ValidationException
     */
    public function create($expId, array $data)
    {
        $data = validator($data, $this->rules())->validate();

        return DB::transaction(function () use ($expId, $data) {
            /** @var ServiceModel $service */
            $service = $this->model::query()->create([
                'express_line_id' => $expId,
                'name' => $data['name'],
                'type' => $data['type'],
                'is_forced' => $data['is_forced'],
                'remark' => $data['remark'] ?? '',
            ]);

            self::updateTrans($data, $service);

            $prices = collect($data['regions'] ?? [])->map(function ($value) use ($expId, $service) {
                return [
                    'express_line_id' => $expId,
                    'region_id' => $value['id'],
                    'service_id' => $service->getKey(),
                    'value' => ($value['value'] ?? 0) * 100,
                    'base_value' => ($value['base_value'] ?? 0) * 100,
                ];
            })->all();

            $service->prices()->createMany($prices);

            return true;
        });
    }

    /**
     * @param $id
     * @param array $data
     * @return mixed
     * @throws ValidationException
     */
    public function update($id, array $data)
    {
        $data = validator($data, $this->rules())->validate();

        return DB::transaction(function () use ($id, $data) {
            /** @var ServiceModel $service */
            $service = $this->model::query()->findOrFail($id);

            $service->update([
                'name' => $data['name'],
                'type' => $data['type'],
                'is_forced' => $data['is_forced'],
                'remark' => $data['remark'] ?? '',
            ]);

            self::updateTrans($data, $service);

            $prices = collect($data['regions'])->map(function ($value) use ($service) {
                return [
                    'express_line_id' => $service->express_line_id,
                    'region_id' => $value['id'],
                    'service_id' => $service->getKey(),
                    'value' => ($value['value'] ?? 0) * 100,
                    'base_value' => ($value['base_value'] ?? 0) * 100,
                ];
            })->all();

            $service->prices()->delete();

            $service->prices()->createMany($prices);

            return true;
        });
    }

    /**
     * @param $id
     * @return mixed
     */
    public function destroy($id)
    {
        return DB::transaction(function () use ($id) {
            /** @var ServiceModel $service */
            $service = $this->model::query()->findOrFail($id);

            $service->prices()->delete();

            $service->delete();

            return true;
        });
    }

    /**
     * @param $orderId
     * @param $expressLineId
     * @return AnonymousResourceCollection
     * @throws Exception
     */
    public function getOrderVASList($orderId, $expressLineId)
    {
        /** @var Order $order */
        $order = Order::query()->findOrFail($orderId);

        $region = $order->getRegionByExpress($expressLineId);

        $vas = ExpressLineVAS::query()
            ->where('express_line_id', $expressLineId)
            ->with(['prices' => function ($query) use ($region) {
                $query->where('region_id', $region['id']);
            }])
            ->get();

        return ExpressLineVASList::collection($vas);
    }

    /**
     * @param $eplId
     * @return bool
     */
    public function export($eplId)
    {
        $items = ExpressLineRegion::query()
            ->with(['servicePrices.service', 'areas'])
            ->where('express_line_id', $eplId)
            ->get();

        $title = $items->first()->servicePrices->map(function ($sp) {
            $feeType = $sp->service->is_forced ? __('强制收取') : __('自愿购买');
            $type = ExpressLineVAS::getTypeName($sp->service->type);

            return sprintf('%s (%s %s)', $sp->service->name, $type, $feeType);
        })->all();

        $first = [__('分区'), __('分区名称'), __('区域'), ...$title];

        $count = 1;
        $data = $items->map(function ($i) use (&$count) {
            $prices = $i->servicePrices->map(fn ($sp) => $sp->value / 100)->all();

           return [
               $count++,
               $i->name,
               mb_substr($i->areas->map(fn ($a) => $a->country_name.$a->area_name.$a->sub_area_name)->join('、'), 0, 32766),
               ...$prices
           ];
        })->all();

        $data = [$first, ...$data];

        $fileName = 'ServicePrices_' . Carbon::now()->format('Ymd') . '_' . Str::random(6) . '.xlsx';

        $filePath = "/excel/prices/$fileName";

        $url = secure_asset(Storage::disk('admin_public')->url($filePath));

        /** @var ExcelExport $export */
        $export = ExcelExport::query()->create([
            'type' => ExcelExport::TYPE_SERVICE_PRICE_TABLE,
            'name' => $fileName,
            'url' => $url,
            'status' => ExcelExport::STATUS_EXPORTING,
        ]);

        dispatch(new RegionServicePriceExport($export, $data));

        return true;
    }

    /**
     * @param $id
     * @param UploadedFile $file
     * @return bool
     * @throws Exception
     */
    public function import($id, UploadedFile $file): bool
    {
        $data = $this->parseData($file);


        $serviceNames = $data->first()->skip(3)->map(function ($v) {
            $names = explode(' ', $v);

            return $names[0];
        })->values()->all();

        $services = ExpressLineVAS::query()
            ->where('express_line_id', $id)
            ->whereIn('name->zh_CN', $serviceNames)
            ->get()->sortBy(function ($s) use ($serviceNames) {
                return array_search($s->name, $serviceNames);
            })->values();

        DB::beginTransaction();
        try {
            foreach ($data->skip(1) as $item) {
                $region = ExpressLineRegion::query()
                    ->where('express_line_id', $id)
                    ->where('name->zh_CN', $item[1])
                    ->first();

                if (!$region) {
                    throw new AccidentException("区域{$item[1]}不存在", Code::OPERATE_FAIL);
                }

                foreach ($services as $key => $service) {
                    ExpressLineServicePrice::query()
                        ->where('region_id', $region->getKey())
                        ->where('service_id', $service->getKey())
                        ->update(['value' => ($item[$key + 3]) * 100]);
                }
            }
        } catch (Exception $exception) {
            throw $exception;
        } catch (\Throwable $throwable) {
            DB::rollBack();

            info('价格表导入失败', ['message' => $throwable->getMessage()]);

            throw new AccidentException('导入失败，请检查Excel数据格式', Code::OPERATE_FAIL);
        }

        DB::commit();

        return true;
    }

    /**
     * @param UploadedFile $file
     * @return Collection
     * @throws Exception
     */
    protected function parseData(UploadedFile $file): Collection
    {
        try {
            $config = ['path' => $file->getPath()];

            $excel = (new Excel($config))
                ->openFile($file->getFilename())
                ->openSheet();

            $items = collect([]);
            while (($row = $excel->nextRow()) !== null) {
                if (!$row[0]) {
                    break;
                }
                $items->push(collect($row));
            }

            return $items;
        } catch (\Throwable $throwable) {
            throw new AccidentException('模板数据异常，请检查模板数据是否填写完整与正确', Code::OPERATE_FAIL);
        }
    }

    /**
     * @return string[]
     */
    protected function rules()
    {
        return [
            'name' => 'required|string|max:32',
            'type' => 'required|integer',
            'is_forced' => 'required|bool',
            'remark' => 'sometimes|nullable|string|max:512',
            'regions' => 'array',
            'regions.*.id' => 'required',
            'regions.*.value' => 'sometimes|nullable|numeric',
            'regions.*.base_value' => 'sometimes|nullable|numeric',
            'name_translations' => 'sometimes|nullable|array',
            'remark_translations' => 'sometimes|nullable|array',
        ];
    }
}
