<?php

namespace App\Services\Admin;

use App\Jobs\GenerateInvoice;
use App\Lib\Code;
use App\Models\Admin;
use App\Models\CreditCardRechargeRecord;
use App\Models\ExcelExport;
use App\Models\InvoiceRecords;
use App\Models\Order;
use App\Models\BalanceRecharge;
use App\Models\RechargeApply;
use App\Jobs\Export\InvoiceZipExport;
use App\Services\Client\BaseService;
use App\Services\Traits\InvoiceTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Shopify\Rest\Admin2022_04\Balance;
use App\Exceptions\AccidentException;


/**
 * 发票管理服务类
 * Class InvoiceService
 * @package App\Services\Client
 * @author DonnyLiu <2365057581@qq.com>
 * @date 2024/9/19 19:26
 */
class InvoiceService extends BaseService
{
    use InvoiceTrait;

    public $filterRules = [
        'custom_id' => ['=', 'custom_id'],
        'invoice_no' => ['like', 'invoice_no'],
        'seller_info' => ['like', 'seller_info'],
        'buyer_info' => ['like', 'buyer_info'],
        'source_type' => ['=', 'source_type'],
        'status' => ['=', 'status'],
        'created_at' => ['between', ['create_start_date', 'create_end_date']],
        'invalid_time' => ['between', ['invalid_start_date', 'invalid_end_date']],
    ];

    /**
     * 初始化
     */
    public function __construct()
    {
        $this->model = new InvoiceRecords();
        $this->formData = request()->all();
        $this->query = $this->model->newQuery();
        $this->setFilterRules();
    }

    /**
     * 获取列表
     * @return \Illuminate\Pagination\LengthAwarePaginator
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/19 19:03
     */
    public function index()
    {
        $this->query->with(['custom:id,custom_name,custom_email']);

        $this->query->latest();
        return parent::index(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取详情
     * @param int $id
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed|null
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/19 19:04
     */
    public function show(int $id)
    {
        return $this->query
            ->with(['custom:id,custom_name,custom_email'])
            ->findOrFail($id);
    }

    /**
     * 更新
     * @param int $id
     * @param array $params
     * @return bool
     * @throws \Exception
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/19 19:08
     */
    public function update(int $id, array $params)
    {
        $record = $this->show($id);

        if (isset($params['status']) && $params['status'] == $this->model::INVALID_STATUS) {
            if ($record->status == $this->model::INVALID_STATUS) {
                throw new AccidentException('发票已作废！', Code::OPERATE_FAIL);
            }

            $record->status = $this->model::INVALID_STATUS;
            $record->invalid_time = now()->toDateTimeString();
        }

        $record->updated_at = now()->toDateTimeString();

        return $record->save();
    }

    /**
     * 获取来源
     * @return string[]
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/20 13:55
     */
    public function getSourceTypeList()
    {
        return $this->model::getSourceTypeList();
    }

    /**
     * 申请发票
     * @param $params
     * @return bool
     * @throws \Illuminate\Validation\ValidationException
     * @throws \Exception
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/20 17:50
     */
    public function requestInvoice($params)
    {
        validator($params, $this->requestInvoiceRules(), $this->requestInvoiceMessages())->validate();

        $fileType = $params['file_type'] ?? InvoiceRecords::FILE_TYPE_PDF;
        if (!in_array($fileType, array_keys(InvoiceRecords::getFileTypeList()))) {
            throw new AccidentException('不支持生成的发票文件类型,目前支持PDF/Word/Excel文件', Code::OPERATE_FAIL);
        }

        $adminInfo = Admin::query()->whereNotNull('invoice_info')->first();
        if (empty($adminInfo)) {
            throw new AccidentException('缺少公司的开票信息，请补充后再开票', Code::OPERATE_FAIL);
        }

        $customId = $this->judgeCustomIsUnique($params['ids'], $params['type']);
        $ids = $params['ids'];
        $type = $params['type'];

        if (count($ids) > InvoiceRecords::TYPE_ORDER_GENERATE_MAX_COUNT && $type == InvoiceRecords::TYPE_ORDER) {
            throw new AccidentException('每次最多支持' . InvoiceRecords::TYPE_ORDER_GENERATE_MAX_COUNT . '条订单同时开票，请分批开票!', Code::OPERATE_FAIL);
        }

        $data = [
            'custom_id' => $customId,
            'invoice_no' => $this->generateInvoiceNo($customId, $type),
            'source_type' => (int)$type,
            'file_type' => (int)$fileType,
            'created_at' => now()->toDateTimeString(),
            'status' => 0,
        ];

        DB::beginTransaction();
        try {
            $record = $this->model::query()->create($data);

            $data['id'] = $record->id;
            dispatch(new GenerateInvoice($data, $ids, $adminInfo->toArray()));

        } catch (\Exception $e) {
            info('发票生成失败', ['message' => $e->getMessage(), 'error_code' => $e->getCode()]);
            DB::rollBack();
            return false;
        }
        DB::commit();
        return true;
    }

    /**
     * 判断生成发票的客户id是否唯一
     * @param $ids
     * @param $type
     * @return mixed
     * @throws \Exception
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/25 17:04
     */
    public function judgeCustomIsUnique($ids, $type)
    {
        $customIds = [];

        switch ($type) {
            case $this->model::TYPE_ORDER:
                $customIds = Order::query()->whereIn('id', $ids)->pluck('customer_id');
                break;
            case $this->model::TYPE_TRANSFER_RECHARGE:
                $customIds = RechargeApply::query()->whereIn('id', $ids)->pluck('custom_id');
                break;
            case $this->model::TYPE_ONLINE_RECHARGE:
                $customIds = BalanceRecharge::query()->whereIn('id', $ids)->pluck('custom_id');
                break;
            case $this->model::TYPE_CREDIT_CARD_RECHARGE:
                $customIds = CreditCardRechargeRecord::query()->whereIn('id', $ids)->pluck('custom_id');
                break;
        }

        if (empty($customIds)) {
            throw new AccidentException('没有找到客户信息，请重试');
        }

        $customIds = array_unique($customIds->toArray());
        if (count($ids) > 1 && count($customIds) > 1) {
            throw new AccidentException('不同客户不能同时生成发票，请重试', Code::OPERATE_FAIL);
        }

        return $customIds[0];
    }

    /**
     * 申请发票验证规则
     * @return string[]
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/20 17:50
     */
    public function requestInvoiceRules()
    {
        return [
            'type' => 'required|integer|in:' . implode(',', array_keys($this->getSourceTypeList())),
            'ids' => 'required|array',
        ];
    }

    /**
     * 申请发票验证错误提示
     * @return string[]
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/25 10:47
     */
    public function requestInvoiceMessages()
    {
        return [
            'type.required' => '请选择发票来源',
            'ids.required' => '请选择要生成发票的记录',
        ];
    }

    /**
     * 申请发票压缩包下载
     *
     * @param array $params
     * @return bool
     */
    public function requestInvoiceZip(array $params): bool
    {
        $ids = array_values(array_unique(array_map('intval', $params['ids'] ?? [])));
        if (empty($ids)) {
            throw new AccidentException('请选择要下载的发票记录', Code::OPERATE_FAIL);
        }

        $records = InvoiceRecords::query()
            ->whereIn('id', $ids)
            ->get(['id', 'invoice_no', 'status', 'storage_url']);

        if ($records->count() !== count($ids)) {
            throw new AccidentException('部分发票记录不存在，请刷新后重试', Code::OPERATE_FAIL);
        }

        foreach ($records as $record) {
            if ((int)$record->status !== InvoiceRecords::NORMAL_STATUS) {
                throw new AccidentException('发票状态异常，请稍后再试：' . $record->invoice_no, Code::OPERATE_FAIL);
            }
        }

        $fileName = 'CompressionPackage_' . now()->format('YmdHis') . '.zip';
        $excelExport = ExcelExport::query()->create([
            'type' => ExcelExport::TYPE_INVOICE_ZIP,
            'name' => $fileName,
            'url' => '',
            'status' => ExcelExport::STATUS_EXPORTING,
        ]);

        dispatch(new InvoiceZipExport($excelExport, $records->pluck('id')->toArray()));

        return true;
    }

    /**
     * 更新发票模板
     *
     * @param array $params
     * @return bool
     */
    public function invoiceTemplate(array $params): bool
    {
        $customerId = (int)($params['customer_id'] ?? 0);
        $orderMode = $this->normalizeOrderMode($params['order_mode'] ?? false);
        $template = $params['template'] ?? [];
        $result = 0;

        if ($customerId <= 0 || empty($template)) {
            return false;
        }

        DB::beginTransaction();
        try {
            DB::table('dsp_custom_invoice_style')
                ->where('custom_id', $customerId)
                ->where('order_mode', $orderMode)
                ->whereNull('delete_time')
                ->update([
                    'delete_time' => now()->toDateTimeString(),
                    'updated_at' => now()->toDateTimeString(),
                ]);

            foreach ($template as $labelId) {
                $inserted = DB::table('dsp_custom_invoice_style')->insert([
                    'custom_id' => $customerId,
                    'order_mode' => $orderMode,
                    'label_id' => (int)$labelId,
                    'created_at' => now()->toDateTimeString(),
                    'updated_at' => now()->toDateTimeString(),
                ]);

                if ($inserted) {
                    $result++;
                }
            }
            DB::commit();
        } catch (\Throwable $e) {
            DB::rollBack();
            Log::warning('更新发票模板失败', [
                'message' => $e->getMessage(),
                'customer_id' => $customerId,
                'order_mode' => $orderMode,
            ]);
            return false;
        }

        return $result > 0;
    }

    /**
     * 查看发票模板
     *
     * @param mixed $orderMode
     * @return array
     */
    public function invoiceTemplateGet($orderMode): array
    {
        $orderMode = $this->normalizeOrderMode($orderMode);

        try {
            $labels = DB::table('dsp_invoice_style_label')
                ->where('order_mode', $orderMode)
                ->orderBy('id')
                ->get(['id', 'name']);

            if ($labels->isNotEmpty()) {
                return $labels->map(function ($item) {
                    return [
                        'label' => $item->name,
                        'value' => (int)$item->id,
                    ];
                })->values()->toArray();
            }
        } catch (\Throwable $e) {
            Log::warning('查询发票模板失败，返回默认模板', [
                'message' => $e->getMessage(),
                'order_mode' => $orderMode,
            ]);
        }

        return $this->getDefaultInvoiceTemplate($orderMode);
    }

    /**
     * 查看被选中的发票模板
     *
     * @param mixed $orderMode
     * @param int $customerId
     * @return array
     */
    public function invoiceTemplateGetChecked($orderMode, int $customerId): array
    {
        $orderMode = $this->normalizeOrderMode($orderMode);

        try {
            $ids = DB::table('dsp_custom_invoice_style')
                ->where('custom_id', $customerId)
                ->where('order_mode', $orderMode)
                ->whereNull('delete_time')
                ->orderBy('id')
                ->pluck('label_id')
                ->map(fn ($id) => (int)$id)
                ->toArray();

            if (!empty($ids)) {
                return $ids;
            }
        } catch (\Throwable $e) {
            Log::warning('查询已选发票模板失败，返回默认选中项', [
                'message' => $e->getMessage(),
                'customer_id' => $customerId,
                'order_mode' => $orderMode,
            ]);
        }

        return [1, 2, 3, 4, 5, 6];
    }

    /**
     * 获取默认发票模板
     *
     * @param bool $orderMode
     * @return array
     */
    protected function getDefaultInvoiceTemplate(bool $orderMode): array
    {
        if ($orderMode) {
            return [
                ['label' => 'platformNo', 'value' => 1],
                ['label' => 'productName', 'value' => 2],
                ['label' => 'sku', 'value' => 3],
                ['label' => 'count', 'value' => 4],
                ['label' => 'country', 'value' => 5],
                ['label' => 'amount', 'value' => 6],
                ['label' => 'paymentTime', 'value' => 7],
                ['label' => 'platformOrderNumber', 'value' => 8],
                ['label' => 'systemOrderNumber', 'value' => 9],
                ['label' => 'createTime', 'value' => 10],
            ];
        }

        return [
            ['label' => 'data', 'value' => 1],
            ['label' => 'paymentStyle', 'value' => 2],
            ['label' => 'serialId', 'value' => 3],
            ['label' => 'amount', 'value' => 4],
        ];
    }

    /**
     * 兼容路径参数中的布尔值
     *
     * @param mixed $orderMode
     * @return bool
     */
    protected function normalizeOrderMode($orderMode): bool
    {
        if (is_bool($orderMode)) {
            return $orderMode;
        }

        return in_array(strtolower((string)$orderMode), ['1', 'true', 'yes', 'on'], true);
    }
}
