<?php

/**
 * @Author: h9471
 */

namespace App\Services\Admin;

use App\Exceptions\AccidentException;
use App\Lib\Code;
use App\Models\RemoteDestination;
use App\Models\RemoteType;
use Exception;
use Illuminate\Support\Facades\DB;

/**
 * 偏远类型
 *
 * Class AnnouncementService
 * @package App\Services\Admin
 */
class RemoteTypeService extends BaseService
{
    public $filterRules = [
        'name,operator_name' => ['like', 'keyword'],
        'source' => ['=', 'source']
    ];

    public function __construct()
    {
        $this->request = request();
        $this->formData = $this->request->all();
        $this->model = new RemoteType();
        $this->query = $this->model->newQuery();
        $this->setFilterRules();
    }

    public function all()
    {
        $this->query->select('id', 'name');

        return parent::all(); // TODO: Change the autogenerated stub
    }

    public function store($data)
    {
        $payload = validator($data, $this->rules())->validate();

        $this->model::validateUniqueOrFail('name', $payload['name']);

        $payload['operator_id'] = auth()->id();
        $payload['operator_name'] = auth()->user()->name ?? '';

        return $this->model::query()->create($payload);
    }

    public function update($id, $data)
    {
        $payload = validator($data, $this->rules())->validate();

        $type = $this->model::query()->findOrFail($id);

        RemoteType::validateUniqueOrFail('name', $payload['name'], $id);

        $payload['operator_id'] = auth()->id();
        $payload['operator_name'] = auth()->user()->name ?? '';

        return $type->update($payload);
    }

    public function destroy($data)
    {
        validator($data, $this->destroyRules())->validate();

        throw_if(
            $this->model::query()->whereKey($data['ids'])
                ->where('source', RemoteType::SOURCE_SYSTEM)
                ->first(),
            new AccidentException('偏远类型存在部分来源是系统内置，不可删除，请重新操作', Code::OPERATE_FAIL)
        );

        return DB::transaction(function () use ($data) {

            RemoteType::query()->whereIn('id', $data['ids'])->delete();

            RemoteDestination::query()->where('remote_type_id', $data['ids'])->delete();

            return true;
        });

    }

    // 是否是偏远地区
    public static function isRemoteArea($country, $city, $postCode)
    {
        $country = strtolower($country);
        return RemoteType::query()->whereHas('remoteDestination', function ($query) use ($country, $city, $postCode) {
            $query->where('country_code', $country)->where(function ($query) use ($city, $postCode) {
                $query->where('city', $city)->orWhere('start_postcode', '<=', $postCode)->orWhere('end_postcode', '>=', $postCode);
            });
        })->select('id', 'name')->latest()->first();
    }


    private function rules()
    {
        return [
            'name' => 'required|string|max:100',
            'remark' => 'sometimes|nullable|string|max:150'
        ];
    }

    private function destroyRules()
    {
        return [
            'ids' => 'required|array',
            'ids.*' => 'required|int'
        ];
    }

}
