<?php

/**
 * @Author: h9471
 * @Created: 2020/3/18 16:37
 */

namespace App\Services\Admin;

use App\Exceptions\AccidentException;
use App\Exports\StringExport;
use App\Exports\StringWithExtraExport;
use App\Lib\Code;
use App\Models\AdminLanguages;
use App\Models\SuperAdminStringTranslation;
use Carbon\Carbon;
use Exception;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use Maatwebsite\Excel\Facades\Excel;
use Mavinoo\Batch\Batch;
use Throwable;

class StringTranslationService extends BaseService
{
    use HasBatchDelete;

    public $language;

    protected $filterRules = [
        'key,translation' => ['like', 'keyword'],
    ];

    public function __construct(SuperAdminStringTranslation $stringTran)
    {
        $this->request = request();
        $this->formData = $this->request->all();
        $this->model = $stringTran;
        $this->query = $stringTran->newQuery();
        $this->setFilterRules();
    }

    public function index()
    {
        $this->query->orderByDesc('source');

        return parent::index(); // TODO: Change the autogenerated stub
    }

    /**
     * @param  array  $data
     * @return bool
     * @throws ValidationException|Throwable
     */
    public function create(array $data): bool
    {
        validator($data, $this->rules())->validate();

        throw_if(
            $this->query->where('key', $data['key'])
                ->where('source', $data['source'])
                ->exists(),
            new AccidentException('当前字符串翻译已存在', Code::OPERATE_FAIL)
        );

        $trans = $this->model::query()->create($this->fillData($data));

        $this->rebuildLangCache($trans['company_id'], $trans['source']);

        return true;
    }

    /**
     * @param  int  $id
     * @param  array  $data
     * @return bool
     * @throws ValidationException|Throwable
     */
    public function update(int $id, array $data): bool
    {
        validator($data, $this->rules())->validate();

        /** @var SuperAdminStringTranslation $trans */
        $trans = $this->model::findOrFail($id);

        throw_if(
            $this->query->where('key', $data['key'])
                ->where('source', $data['source'])
                ->whereKeyNot($trans->id)
                ->exists(),
            new AccidentException('当前字符串翻译已存在', Code::OPERATE_FAIL)
        );

        $trans->setTranslations('translation', $data['translation']);

        !empty($data['source']) && $trans->source = $data['source'];

        $trans->save();

        $this->rebuildLangCache($trans['company_id'], $trans['source']);

        return true;
    }

    /**
     * @param  int  $id
     * @return bool
     */
    public function destroy(int $id): bool
    {
        $model = $this->model::query()->findOrFail($id);

        return $model->delete();
    }

    /**
     * @param int $companyId
     * @param int $source
     * @return bool
     */
    public function rebuildLangCache(int $companyId, int $source): bool
    {
        //公司支持的语言
        $languages = AdminLanguages::query()
            ->where('company_id', $companyId)
            ->where('enabled', 1)
            ->pluck('language_code');

        foreach ($languages as $locale) {
            $stringTranslations = SuperAdminStringTranslation::where('source', $source)->get();

            $result = [];

            /** @var SuperAdminStringTranslation $translation */
            foreach ($stringTranslations as $translation) {
                $result[$translation->key] = $translation->getTranslation('translation', $locale);
            }

            $cacheKey = 'StringTranslation_' . $companyId . '_' . $locale . '_' . $source;

            Cache::forever($cacheKey, $result);
        }

        return true;
    }

    /**
     * @return Builder[]|\Illuminate\Database\Eloquent\Collection
     */
    public function getEnabledLanguage(): \Illuminate\Database\Eloquent\Collection|array
    {

        return AdminLanguages::query()
            ->select(['id', 'name', 'language_code'])
            ->where('enabled', 1)
            ->get()->map(function ($value) {
                $value['value'] = '';

                return $value;
            });
    }

    /**
     * @return string
     */
    public function export(): string
    {
        $fileName = 'Strings_' . Carbon::now()->format('Ymd') . '_' . Str::random(6);

        $filePath = "/excel/strings/$fileName.xlsx";

        Excel::store(new StringWithExtraExport($this->getExportData(), $this->getLanguageData()), admin_path($filePath), 'cos');

        return secure_asset(Storage::disk('admin_public')->url($filePath));
    }


    private function getExportData()
    {
        return SuperAdminStringTranslation::query()
            ->select(['id', 'key', 'source'])
            ->orderBy('source','desc')
            ->get();
    }

    private function getLanguageData()
    {
        return AdminLanguages::query()
            ->select(['id', 'name', 'language_code'])
            ->where('enabled', 1)
            ->get();
    }

    /**
     * @throws Throwable
     */
    public function import(UploadedFile $file)
    {
        $data = $this->parseData($file);

        throw_if(
            !AdminLanguages::query()->where('language_code', $this->language)->first(),
            new AccidentException('不支持当前语言翻译，请在支持语言的菜单中，检查是否已经开启该语言', Code::OPERATE_FAIL)
        );

        $batch = new Batch(app('db'));
        $model = new SuperAdminStringTranslation();
        try {
            DB::transaction(function () use ($data, $batch, $model){
                $companyId = auth()->user()->company_id;
                $data->chunk(300)->each(function ($tmpData) use ($batch, $model, $companyId){
                    $strings = [];
                    $inserts = [];
                    $tmpData->each(function ($s) use (&$strings, &$inserts){
                        $now = now()->toDateTimeString();
                        if (!empty($s[0]) && !empty($s[3])) {
                            $strings[] = [
                                'id' => $s[0],
                                'translation' => DB::raw("JSON_SET(translation, '$.{$this->language}', '{$s[3]}')"),
                                'updated_at' => DB::raw("'{$now}'")
                            ];
                        } elseif(empty($s[0]) && !empty($s[3])) {
                            $inserts[] = [
                                'key' => $s[1],
//                                'translation' => DB::raw("JSON_SET(translation, '$.{$this->language}', '{$s[3]}')"),
                                'translation' => json_encode([$this->language => $s[3], 'zh_CN' => $s[1]]),
                                'company_id' => auth()->user()->company_id,
                                'source' => $s[2] == 'PC网站' ? 1 : ($s[2] == '小程序' ? 3 : 2), // 1-PC网站 2-API 3-H5/小程序
                                'updated_at' => now(),
                                'created_at' => now()
                            ];
                        }
                    });
                    $strings && $batch->update($model, $strings, raw:true);
                    $inserts && $this->model::insert($inserts);
                    Cache::forever('StringTranslation_' . $companyId . '_flush', 1);
                });
            });
        }catch (Throwable $th){
            info('string-message', ['message' => $th->getMessage()]);
            throw new AccidentException('字符串导入失败,请检查数据是否正确', Code::OPERATE_FAIL);
        }
        return true;
    }


    /**
     * @param UploadedFile $file
     * @return Collection
     * @throws Exception
     */
    protected function parseData(UploadedFile $file)
    {
        try {
            $config = ['path' => $file->getPath()];

            $excel = (new \Vtiful\Kernel\Excel($config))
                ->openFile($file->getFilename())
                ->openSheet();

            $items = collect([]);
            while (($row = $excel->nextRow()) !== null) {
                if (!$row) {
                    break;
                }
                $items->push(collect($row));
            }
            $this->language = $items[0][3] ?? '';
            unset($items[0]);

            return $items;
        } catch (Throwable $throwable) {
            info($throwable->getMessage());
            info($throwable->getLine());
            throw new AccidentException('模板数据异常，请检查模板数据是否填写完整与正确', Code::OPERATE_FAIL);
        }
    }


    /**
     * @param  array  $data
     * @return array
     */
    protected function fillData(array $data)
    {
        return [
            'key' => $data['key'] ?? '',
            'source' => $data['source'] ?? SuperAdminStringTranslation::PC,
            'translation' => $data['translation'] ?? '{}',
        ];
    }

    /**
     * @return array
     */
    private function rules()
    {
        return [
            'key' => 'required|string|max:500',
            'source' => 'nullable',
            'translation' => 'nullable|array',
        ];
    }
}
