<?php

namespace App\Services\Client;

use App\Lib\Code;
use App\Models\AfterSalesWorkOrder;
use App\Models\AfterSalesWorkOrderLogs;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Cache;
use Illuminate\Validation\ValidationException;
use App\Exceptions\AccidentException;

/**
 * 客户端售后工单服务类
 * Class AfterSalesWorkOrderService
 * @package App\Services\Client
 * @author DonnyLiu <2365057581@qq.com>
 * @date 2024/9/6 16:51
 */
class AfterSalesWorkOrderService extends BaseService
{
    public $filterRules = [
        'status'        => ['=', 'status'],
        'work_order_id' => ['like', 'work_order_id'],
        'desc'          => ['like', 'desc'],
        'type'          => ['=', 'type'],
        'created_at'    => ['between', ['begin_date', 'end_date']],
    ];

    /**
     * 最大上传文件数量
     */
    public const DEFAULT_MAX_FILE_UPLOADS = 5;

    /**
     * 初始化
     * @param AfterSalesWorkOrder $model
     */
    public function __construct(AfterSalesWorkOrder $model)
    {
        $this->model = $model;
        $this->query = $model->newQuery();
        $this->formData = request()->all();
        $this->setFilterRules();
    }

    /**
     * 获取列表
     * @return \Illuminate\Pagination\LengthAwarePaginator
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 17:28
     */
    public function index()
    {
        if (!isset($this->formData['size'])) $this->formData['size'] = 20;

        $this->query->with(['custom', 'handleAdmin'])
            ->where('custom_id', getCustomId());

        $this->query->latest();

        return parent::index();
    }

    /**
     * 获取详情
     * @param $id
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed|null
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 17:27
     */
    public function show($id)
    {
        $this->query->with(['custom', 'handleAdmin']);

        return $this->query->findOrFail($id); // TODO: Change the autogenerated stub
    }

    /**
     * 新增
     * @param array $data
     * @return mixed
     * @throws ValidationException
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 19:10
     */
    public function store(array $data)
    {
        validator($data, $this->getStoreRules())->validate();

        if (!empty($data['attachment_url'])) {
            $length = count($data['attachment_url']);
            $maxFileUploads = $data['max_file_uploads'] ?? self::DEFAULT_MAX_FILE_UPLOADS;
            if ($length > $maxFileUploads) {
                throw new AccidentException('附件上传数量超过限制，最多支持上传'.  $maxFileUploads . '个附件', Code::OPERATE_FAIL);
            }
        }

        return DB::transaction(function () use ($data) {
            $customId = getCustomId();

            $insertData = [
                'custom_id'             => $customId,
                'work_order_id'         => $this->generateWorkOrderId($customId),
                'reference_order_id'    => $data['reference_order_id'] ?? '',
                'desc'                  => $data['desc'],
                'type'                  => $data['type'],
                'attachment_url'        => $data['attachment_url'] ?? [],
                'status' => 1,
            ];

            $result = $this->query->create($insertData);
            if ($result) {
                //记录工单操作日志
                AfterSalesWorkOrderLogs::query()->create([
                    'work_order_id' => $result->id,
                    'custom_id'     => $customId,
                    'type'          => $insertData['status'],
                    'content'       => "客户ID：{$customId} 创建了工单",
                    'handle_id'     => 0,
                ]);
            }

            return true;
        });
    }

    /**
     * 获取工单类型
     * @return array
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 19:35
     */
    public function getTypeList()
    {
        return $this->model->getTypeList();
    }

    /**
     * 获取验证规则
     * @return string[]
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 19:03
     */
    public function getStoreRules()
    {
        return [
            'reference_order_id'    => 'nullable',
            'desc'                  => 'required|string|max:500',
            'type'                  => 'required|int|in:'. implode(',', array_column($this->getTypeList(), 'id')),
            'attachment_url'        => 'sometimes|nullable|array',
            'attachment_url.*.name' => 'sometimes|nullable|string',
            'attachment_url.*.path' => 'sometimes|nullable|string',
            'max_file_uploads'      => 'sometimes|nullable|int',

        ];
    }

    /**
     * 生成工单号
     * @param int $customId
     * @return string
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/6 19:02
     */
    public function generateWorkOrderId(int $customId)
    {
        $key = "WO". str_pad($customId, 4, '0', STR_PAD_LEFT) . date('Ymd');

        if (($id = Cache::get($key))) {
            $value = $id + 1;
            Cache::increment($key);
        } else {
            $value = 1;
            Cache::put($key, $value, (Carbon::now()->endOfDay()->unix() - Carbon::now()->unix()));
        }

        return $key . str_pad($value, 2, '0', STR_PAD_LEFT);
    }

}
