<?php

namespace App\Services\Client;

use App\Models\Country;
use App\Models\CustomAddress;
use App\Lib\Code;
use Illuminate\Http\Request;
use Exception;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use App\Exceptions\AccidentException;

/**
 * 客户地址管理服务类
 * Class CustomAddressService
 * @package App\Services\Client
 * @author DonnyLiu <2365057581@qq.com>
 * @date 2024/8/29 19:59
 */
class CustomAddressService extends BaseService
{
    public $filterRules = [
        'first_name,last_name,phone_number' => ['like', 'search'],
        'country_id' => ['=', 'country_id'],
    ];

    /**
     * 初始化
     */
    public function __construct()
    {
        $this->model = new CustomAddress();
        $this->formData = request()->all();
        $this->query = $this->model->newQuery();
        $this->setFilterRules();
    }

    /**
     * 列表
     * @return \Illuminate\Pagination\LengthAwarePaginator
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/8/29 20:18
     */
    public function index()
    {
        if (!isset($this->formData['size'])) $this->formData['size'] = 1000;

        $this->query->with([
            'custom',
            'country',
        ])->where('custom_id', getCustomId())
        ->whereNull('deleted_at');

        $this->query->orderByDesc('is_default');

        $this->query->latest();

        return parent::index(); // TODO: Change the autogenerated stub
    }

    /**
     * 详情
     * @param $id
     * @return mixed
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/8/29 20:18
     */
    public function show($id)
    {
        return $this->model::query()->with([
            'custom',
            'country',
        ])->whereNull('deleted_at')->where('custom_id', getCustomId())->findOrFail($id); // TODO: Change the autogenerated stub
    }

    /**
     * 创建数据
     * @param $params
     * @return mixed
     * @throws \Illuminate\Validation\ValidationException
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/8/29 20:36
     */
    public function store($params)
    {
        validator($params, $this->rules())->validate();

        return DB::transaction(function () use ($params) {
            $country = Country::query()->findOrFail($params['country_id']);
            $params['country_code'] = $country->code;
            if (!empty($params['is_default'])) {
                $this->query->where('custom_id', getCustomId())->update(['is_default' => 0]);
            }
            $data = $this->fillData($params);
            $data['custom_id'] = getCustomId();

            return $this->query->create($data);
        });
    }

    /**
     * 更新
     * @param $id
     * @param $params
     * @return mixed
     * @throws \Illuminate\Validation\ValidationException
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/8/29 20:39
     */
    public function update($id, $params)
    {
        $address = $this->show($id);
        if ($address->custom_id != getCustomId()) {
            throw new AccidentException('无编辑权限', Code::OPERATE_FAIL);
        }

        validator($params, $this->rules())->validate();

        return DB::transaction(function () use ($params, $address) {
            $country = Country::query()->findOrFail($params['country_id']);
            $params['country_code'] = $country->code;
            if (!empty($params['is_default'])) {
                $this->query->where('custom_id', getCustomId())->where('id', '!=', $address->id)->update(['is_default' => 0]);
            }
            $data = $this->fillData($params);

            $address->update($data);

            return true;
        });
    }

    /**
     * @param $params
     * @return bool
     * @throws \Throwable
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/8/29 20:23
     */
    public function deletes($params): bool
    {
        $ids = $params['ids'] ?? [];
        throw_if(!$ids, new AccidentException('请选择要删除的地址', Code::OPERATE_FAIL));

        return DB::transaction(function () use ($ids) {
            $this->query->where('custom_id', getCustomId())->whereIn('id', $ids)->delete();

            return true;
        });
    }

    /**
     * 设置默认地址
     * @param $id
     * @return true
     * @throws \Throwable
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/8/29 20:31
     */
    public function setDefault($id)
    {
        $address = $this->query->where('custom_id', getCustomId())->findOrFail($id);

        $this->query->where('custom_id', getCustomId())->update(['is_default' => 0]);

        $address->is_default = 1;
        $address->save();

        return true;
    }

    /**
     * 填充数据
     * @param $data
     * @return array
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/8/29 20:35
     */
    public function fillData($data)
    {
        return [
            'first_name'        => $data['first_name'],
            'last_name'         => $data['last_name'],
            'country_id'        => $data['country_id'],
            'province'          => $data['province'] ?? '',
            'city'              => $data['city'],
            'address_detail'    => $data['address_detail'],
            'phone_number'      => $data['phone_number'],
            'email'             => $data['email']  ?? '',
            'post_code'         => $data['post_code'],
            'tax_id'            => $data['tax_id'] ?? '',
            'is_default'        => $data['is_default'] ?? 0,
            'name'              => $data['first_name'] . ' ' . $data['last_name'],
            'country_code'      => $data['country_code'] ?? '',
            'province_code'     => $data['province_code'] ?? '',
            'address_type'      => $data['address_type'] ?? 'shipping',
            'phone_area_code'   => $data['phone_area_code'] ?? ''
        ];
    }
    /**
     * 验证规则
     * @return string[]
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/8/29 20:29
     */
    public function rules()
    {
        return [
            'first_name' => 'required|string',
            'last_name' => 'required|string',
            'country_id' => 'required|int',
            'province' => 'nullable|string',
            'city' => 'required|string',
            'address_detail' => 'required|string',
            'phone_number' => 'required|string',
            'email' => 'nullable|string',
            'post_code' => 'required|string',
            'tax_id' => 'nullable|string',
            'address_type' => 'sometimes|nullable|in:billing,shipping'
        ];
    }
}
