<?php

namespace App\Services\Client;

use App\Lib\Code;
use App\Jobs\GenerateInvoice;
use App\Models\Admin;
use App\Models\CustomInvoiceAddressModel;
use App\Models\InvoiceRecords;
use App\Services\ApiResponseService;
use App\Services\Traits\InvoiceTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Exceptions\AccidentException;

/**
 * 发票管理服务类
 * Class InvoiceService
 * @package App\Services\Client
 * @author DonnyLiu <2365057581@qq.com>
 * @date 2024/9/19 19:26
 */
class InvoiceService extends BaseService
{
    use InvoiceTrait;

    public $filterRules = [
        'invoice_no' => ['like', 'invoice_no'],
        'seller_info' => ['like', 'seller_info'],
        'buyer_info' => ['like', 'buyer_info'],
        'source_type' => ['=', 'source_type'],
        'status' => ['=', 'status'],
        'created_at' => ['between', ['create_start_date', 'create_end_date']],
        'invalid_time' => ['between', ['invalid_start_date', 'invalid_end_date']],
    ];

    /**
     * 初始化
     */
    public function __construct()
    {
        $this->model = new InvoiceRecords();
        $this->formData = request()->all();
        $this->query = $this->model->newQuery();
        $this->setFilterRules();
    }

    /**
     * 获取列表
     * @return \Illuminate\Pagination\LengthAwarePaginator
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/19 19:03
     */
    public function index()
    {
        $this->query->with(['custom:id,custom_name,custom_email']);

        $this->query->where('custom_id', getCustomId());

        $this->query->latest();
        return parent::index(); // TODO: Change the autogenerated stub
    }

    /**
     * 获取详情
     * @param int $id
     * @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model|mixed|null
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/19 19:04
     */
    public function show(int $id)
    {
        return $this->query
            ->with(['custom:id,custom_name,custom_email'])
            ->findOrFail($id);
    }

    /**
     * 更新
     * @param int $id
     * @param array $params
     * @return bool
     * @throws \Exception
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/19 19:08
     */
    public function update(int $id, array $params)
    {
        $record = $this->show($id);

        if (isset($params['status']) && $params['status'] == $this->model::INVALID_STATUS) {
            if ($record->status == $this->model::INVALID_STATUS) {
                throw new AccidentException('发票已作废！', Code::OPERATE_FAIL);
            }

            $record->status = $this->model::INVALID_STATUS;
            $record->invalid_time = now()->toDateTimeString();
        }

        $record->updated_at = now()->toDateTimeString();

        return $record->save();
    }

    /**
     * 获取来源
     * @return string[]
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/20 13:55
     */
    public function getSourceTypeList()
    {
        return $this->model::getSourceTypeList();
    }

    /**
     * 申请发票
     * @param $params
     * @return bool
     * @throws \Illuminate\Validation\ValidationException
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/20 17:50
     */
    public function requestInvoice($params)
    {
        validator($params, $this->requestInvoiceRules(), $this->requestInvoiceMessages())->validate();

        $fileType = $params['file_type'] ?? InvoiceRecords::FILE_TYPE_PDF;
        if (!in_array($fileType, array_keys(InvoiceRecords::getFileTypeList()))) {
            throw new AccidentException('不支持生成的发票文件类型,目前支持PDF/Word/Excel文件', Code::OPERATE_FAIL);
        }

        $adminInfo = Admin::query()->whereNotNull('invoice_info')->first();
        if (empty($adminInfo)) {
            throw new AccidentException('缺少公司的开票信息，请补充后再开票', Code::OPERATE_FAIL);
        }

        $customId = getCustomId();

        //客户开票信息
        $customerInvoiceInfo = CustomInvoiceAddressModel::query()->where('customer_id', $customId)->first();
        if (empty($customerInvoiceInfo)) {
            throw new AccidentException('缺少开票信息，请在“设置-发票信息”设置后再操作', Code::OPERATE_FAIL);
        }

        $ids = $params['ids'];
        $type = $params['type'];

        if (count($ids) > InvoiceRecords::TYPE_ORDER_GENERATE_MAX_COUNT && $type == InvoiceRecords::TYPE_ORDER) {
            $message = sprintf(__('每次最多支持%d条订单同时开票，请分批开票!'), InvoiceRecords::TYPE_ORDER_GENERATE_MAX_COUNT);

            throw new AccidentException($message, Code::OPERATE_FAIL);
        }

        $data = [
            'custom_id'     => $customId,
            'invoice_no'    => $this->generateInvoiceNo($customId, $type),
            'source_type'   => (int)$type,
            'file_type'     => (int)$fileType,
            'created_at'    => now()->toDateTimeString(),
            'status'        => 0,
        ];

        DB::beginTransaction();
        try {
            $record = $this->model::query()->create($data);

            $data['id'] = $record->id;
            dispatch(new GenerateInvoice($data, $ids, $adminInfo->toArray()));
        } catch (\Exception $e) {
            info('发票生成失败', ['message' => $e->getMessage(), 'error_code' => $e->getCode()]);
            DB::rollBack();
            return false;
        }
        DB::commit();
        return true;
    }

    /**
     * 申请发票验证规则
     * @return string[]
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/20 17:50
     */
    public function requestInvoiceRules()
    {
        return [
            'type'  => 'required|integer|in:'. implode(',', array_keys($this->getSourceTypeList())),
            'ids'   => 'required|array',
        ];
    }

    /**
     * 申请发票验证错误提示
     * @return string[]
     * @author DonnyLiu <2365057581@qq.com>
     * @date 2024/9/25 10:47
     */
    public function requestInvoiceMessages()
    {
        return [
            'type.required' => '请选择发票来源',
            'ids.required'  => '请选择要生成发票的记录',
        ];
    }
}
