access.log = /var/log/phpaccess.$pool.log
access.format = "%R - %u %t \"%m %r%Q%q\" %s %f %{mili}d %{kilo}M %{system}C%%"
slowlog = /var/log/phpslow.$pool.log
request_slowlog_timeout = 3s

[www]
pm.max_children = 100
pm.start_servers = 15
pm.min_spare_servers = 10
pm.max_spare_servers = 20
pm.status_path = /jf-status
pm.max_requests = 10240
request_terminate_timeout = 400
